CREATE TABLE BOOK.AUTHORS
(
	AuthorID INT NOT NULL AUTO_INCREMENT,
    firstName VARCHAR(20) NOT NULL,
    lastName VARCHAR(30) NOT NULL,
    PRIMARY KEY ( AuthorID )
);

CREATE TABLE BOOK.TILTLES
(
	ISBN VARCHAR(20) NOT NULL,
    TiTle VARCHAR(100) NOT NULL,
	EdiltionNumber INT NOT NULL,
    CopyRight VARCHAR(4),
    PRIMARY KEY (ISBN)
);

CREATE TABLE BOOK.AUTHORLSBN
(
	Authour INT NOT NULL ,
	ISBN VARCHAR(20) NOT NULL,
    FOREIGN KEY (AuthorID) REFERENCES BOOK.AUTHORS(AuthorID),
        FOREIGN KEY (ISBN) REFERENCES BOOK.TILTLES(ISBN)
);